### ISSUE TITLE
Don't respond with a WWW-Authenticate header

### ISSUE THREAD

**Issue by michael** [michael/hub#10]
Related to username/pwd prompt problem.

https://github.com/substance/composer/issues/264#issuecomment-12825037

**Comment by michael** [comment]
This has high priority. Since it overwrites Authorization: token TOKEN with the basic auth on each request.

**Comment by yuchi** [comment]
Solved by 2a2cb62bd0ae5df4d4bb50ebc20e98a309b7328c

**Comment by yuchi** [comment]
Can you please test it a little? I do not have a Composer here!

**Comment by michael** [comment]
yeah. thanks. will do.

**Comment by michael** [comment]
the login dialog doesn't get prompted anymore... but then i can't login with my credentials. :(

**Comment by yuchi** [comment]
What happens exactly?

**Comment by michael** [comment]
It fails like so:

```
[object Object]
    at /Users/michael/projects/hub/routes/api/index.js:41:56
    at allFailed (/Users/michael/projects/hub/node_modules/passport/lib/passport/middleware/authenticate.js:87:18)
    at attempt (/Users/michael/projects/hub/node_modules/passport/lib/passport/middleware/authenticate.js:231:28)
    at Context.module.exports.delegate.fail (/Users/michael/projects/hub/node_modules/passport/lib/passport/middleware/authenticate.js:226:9)
    at Context.actions.fail (/Users/michael/projects/hub/node_modules/passport/lib/passport/context/http/actions.js:35:22)
    at BasicStrategy.authenticate (/Users/michael/projects/hub/node_modules/passport-http/lib/passport-http/strategies/basic.js:68:37)
    at attempt (/Users/michael/projects/hub/node_modules/passport/lib/passport/middleware/authenticate.js:243:16)
    at Passport.authenticate (/Users/michael/projects/hub/node_modules/passport/lib/passport/middleware/authenticate.js:244:7)
    at /Users/michael/projects/hub/routes/api/index.js:32:47
    at callbacks (/Users/michael/projects/hub/node_modules/express/lib/router/index.js:161:37)
```

**Comment by michael** [comment]
Try curl with proper username/password credentials, you'll see.

**Comment by yuchi** [comment]
Against which route?

**Comment by yuchi** [comment]
I tested it against POST /authentications and worked like a charm :(

**Comment by michael** [comment]
oh... is there a new route now?

i thought it's `POST /authorizations`.

**Comment by yuchi** [comment]
Sorry, my fault, I still confuse them. It's exact, it's still /authorizations.

**Comment by yuchi** [comment]
I try it again

**Comment by michael** [comment]
```
  return function (req, res, next, err, object, info) {
    if (err || !object) {
      console.log('error?', err, 'object: ', object);
      next(new errors.Unauthorized(err ? err.message : message));
      // next('message');
    } else {
      req[property] = object;
      next();
    }
  };
```

object is false.

**Comment by yuchi** [comment]
```
~ pier $ curl -X POST http://localhost:3000/api/v1/authorizations
{
  "name": "Unauthorized",
  "message": "Authentication failed",
  "status": 401
}

~ pier $ curl -X POST http://localhost:3000/api/v1/authorizations -u admin
Enter host password for user 'admin':
{
  "name": "Unauthorized",
  "message": "Wrong Application credentials",
  "status": 401
}

~ pier $ curl -X POST http://localhost:3000/api/v1/authorizations -u admin -d "client_id=10ab06a48395379bc8a50eda8d9dd40&client_secret=8aa349f90f24eb971437b4e00e2558c2"
Enter host password for user 'admin':
{
  "uuid": "0128553b2dc833ace90159340ff5466c",
  "active": true,
  "user_uuid": "admin",
  "application_uuid": "10ab06a48395379bc8a50ed3a8d9dd40",
  "token": "4c169ccc7ede5f517b63d8d7dfbfb1f0",
  "scopes": "all",
  "created_at": "2013-02-01T15:01:41.571Z"
}

~ pier $ 
```

**Comment by yuchi** [comment]
That means that the authentication actually failed! Strange!

**Comment by michael** [comment]
Hm.. it works with curl now... but not from within the app :/

```
}dubmac:~ michael$ curl -i -X POST http://localhost:3000/api/v1/authorizations -u michael -d"client_id=f7043dc691102f3ac3175e606af2c8cb&client_secret=ca85e9a193c721e5d65eba26164c0d87"
Enter host password for user 'michael':
HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 260
Set-Cookie: connect.sid=s%3Arg0%2FW7rTXt8JtSXGWWS8MPza.xVNsnJMwHaXmB4YJdv6HJcmJLQlRYgAWr5mWprdkMuY; Path=/; HttpOnly
Date: Fri, 01 Feb 2013 14:54:49 GMT
Connection: keep-alive

{
  "uuid": "b9e5da6ad3ee4a99b2d06110f458c09a",
  "active": true,
  "user_uuid": "michael",
  "application_uuid": "f7043dc691102f3ac3175e606af2c8cb",
  "token": "752775a3208de5dca9ded94c1d726cd3",
  "scopes": "all",
  "created_at": "2013-01-30T10:27:45.805Z"
```

**Comment by michael** [comment]
Here's the code I'm using:

```
function authenticate(options, cb) {
  $.ajax({
    type: 'POST',
    url: Substance.settings.hub_api + '/authorizations',
    accepts: "application/substance.v1+json",
    data: {
      "client_id": Substance.settings.client_id,
      "client_secret": Substance.settings.client_secret
    },
    success: function(result) {
      if (result.status === "error") return cb('Login failed. Check your input.');
      cb(null, result);
    },
    error: function() {
      cb('Login failed. Check your input.');
    },
    username: options.username,
    password: options.password
  });
}
```

any ideas?

**Comment by yuchi** [comment]
Pretty obvious: jQuery username/password does not use the Authorization Header, uses the url as `user:pass@host:port/` And somehow I do not support it.

Could you please rollback to your old version which sent the Header as `"Basic "+base64Encode(username + ":" + password)`? (I'm going to address the url support in another issue)

**Comment by yuchi** [comment]
Whoops... Probably related: http://stackoverflow.com/questions/9721473/ajax-authorization-header-has-not-been-sent

**Comment by michael** [comment]
I had to remove:

```
// accepts: "application/substance.v1+json",
```

and use the header instead of username, password keys... it works now. :)

**Comment by yuchi** [comment]
Mh... A bunch of issues are coming to the hub!

**Comment by yuchi** [comment]
The `accepts` issue is now #23
